name: deploy-to-nginx
on: [push]
jobs:
  bundle-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload content
        uses: actions/upload-artifact@v1
        with:
          name: web-artifacts
          path: www
          retention-days: 1

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 37.120.168.244
          username: root
          password: HTP5PTpEQsHwHNE
          # source: web-artifacts.zip
          source: www/*.*
          target: "www"
