name: deploy-to-nginx
on: [push]
jobs:
  bundle-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload content
        uses: actions/upload-artifact@v2
        with:
          name: web-artifacts
          path: www
          retention-days: 1

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: web-artifacts
          path: deploy-to-nginx

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          username: root
          # host: 37.120.168.244
          # password: HTP5PTpEQsHwHNE
          host: 185.183.159.67
          password: 351mu8dUWhzd4Bk
          source: "deploy-to-nginx/*.*"
          target: "/var/www/html/deploy-to-nginx"
