name: deploy-to-nginx
on: [push]
jobs:
  bundle-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload content
        uses: actions/upload-artifact@v2
        with:
          name: web-artifacts
          path: www
          retention-days: 1

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: web-artifacts
          path: deploy-to-nginx

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: 185.183.159.67
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}
          source: "deploy-to-nginx/*.*"
          target: "/var/www/html"
